=== ARuiz3/lenguajedemarcas/actividad13/tabla.dtd
<!ELEMENT esquema (mensaje)>
<!ELEMENT mensaje (remite,destinatario,texto)>
<!ATTLIST mensaje asunto CDATA #REQUIRED>
<!ELEMENT remite (nombre,email)>
<!ELEMENT destinatario (nombre,email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT texto (parrafo+)>
<!ELEMENT parrafo (#PCDATA)>

=== ARuiz3/lenguajedemarcas/actividad13/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE esquema SYSTEM "tabla.dtd">
<esquema>
    <mensaje asunto="Hola Bill">
        <remite>
            <nombre>Alfredo Reino</nombre>
            <email>alf@ibium.com</email>
        </remite>
        <destinatario>
            <nombre>Bill Clinton</nombre>
            <email>president@whitehouse.gov</email>
        </destinatario>
        <texto>
            <parrafo>Â¿Hola que tal?</parrafo>
            <parrafo>...</parrafo>
        </texto>
    </mensaje>
</esquema>
